[admin]
log_level = "INFO"

[proxy]
[[proxy.configs]]
listen_addr = "0.0.0.0:9088"
username = "root"
password = "12345678"
db = "mixer"
backend_type = "mysql"
nodes = ["node001"]

[mysql]
[[mysql.nodes]]
name = "node001"
user = "root"
password = "12345678"
addr = "192.168.33.10:3306"
db = "mixer"